import { Head, Link } from '@inertiajs/react';

type History = { id: string; assessed_at: string; activity_name_snapshot: string; rubric_name: string; rubric_version: number; final_score: string; passed: number | boolean; grade_label_snapshot: string | null };
type Progress = { id: string; program_name: string; version: number; version_name: string; active: boolean; unique_ayahs: number; target_ayahs: number; percent: number; sessions: number };
type Mistake = { surah: string; surah_number: number; ayah_number: number; rule_name: string; event_count: number; session_count: number };
type Props = { student: { id: string; name: string; code: string }; summary: { sessions: number; murajaah: number; last_ayah: { surah: string; surah_number: number; ayah_number: number } | null }; progress: Progress[]; mistakes: Mistake[]; history: { data: History[]; current_page: number; last_page: number; prev_page_url: string | null; next_page_url: string | null } };

export default function StudentReport({ student, summary, progress, mistakes, history }: Props) {
    return <div className="master-shell"><Head title={`Progres ${student.name}`} /><a className="skip-link" href="#student-report">Lewati navigasi</a><header className="mushaf-header"><Link href="/reports">← Laporan</Link><span>Penilaian Tahfidz · Progres santri</span></header>
        <main id="student-report" className="master-main"><p className="eyebrow">Profil santri</p><h1>{student.name}</h1><p className="muted">{student.code} · {summary.sessions} sesi final · {summary.murajaah} murajaah</p>
            <section className="master-card"><h2>Posisi terakhir</h2><p>{summary.last_ayah ? `${summary.last_ayah.surah} ${summary.last_ayah.surah_number}:${summary.last_ayah.ayah_number}` : 'Belum dicatat.'}</p></section>
            <section className="master-card"><h2>Hafalan unik per enrollment</h2><p className="muted">Jumlah ayat unik dari bacaan aktual yang lulus dan kegiatan berkontribusi, dibatasi target versi program. Persentase ini menghitung ayat, bukan panjang bacaan.</p>{progress.length === 0 && <p>Belum ada enrollment program.</p>}{progress.map((item) => <article className="master-row" key={item.id}><div><strong>{item.program_name} · v{item.version}</strong><p>{item.version_name} · {item.active ? 'Aktif' : 'Riwayat'} · {item.sessions} sesi</p></div><div><strong>{item.unique_ayahs} / {item.target_ayahs} ayat</strong><br /><span>{item.percent}%</span></div></article>)}</section>
            <section className="master-card"><h2>Lokasi kesalahan</h2><p className="muted">Jumlah kejadian dan jumlah sesi yang menilai lokasi ini; angka tersebut bukan persentase akurasi.</p>{mistakes.length === 0 && <p>Belum ada kesalahan aktif pada hasil final.</p>}{mistakes.map((item, index) => <p key={index}>{item.surah} {item.surah_number}:{item.ayah_number} · {item.rule_name}: {item.event_count} kejadian dalam {item.session_count} sesi</p>)}</section>
            <section className="master-card"><h2>Riwayat nilai</h2>{history.data.length === 0 && <p>Belum ada hasil final.</p>}{history.data.map((item) => <article className="master-row" key={item.id}><div><strong>{item.activity_name_snapshot}</strong><p>{item.assessed_at?.slice(0, 10)} · {item.rubric_name} v{item.rubric_version}</p></div><div>{item.final_score} · {item.passed ? 'Lulus' : 'Belum lulus'}{item.grade_label_snapshot ? ` · ${item.grade_label_snapshot}` : ''}</div></article>)}<div className="master-actions report-pagination">{history.prev_page_url && <Link href={history.prev_page_url}>Sebelumnya</Link>}<span>Halaman {history.current_page} dari {history.last_page}</span>{history.next_page_url && <Link href={history.next_page_url}>Berikutnya</Link>}</div></section>
        </main>
    </div>;
}
