import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';

type Rule = { id?: string; name: string; severity_label: string | null; deduction_points: string };
type Criterion = { id?: string; name: string; description: string; method: 'direct' | 'deduction'; min_score: string; max_score: string; weight: string; min_pass_normalized: string | null; rules: Rule[] };
type Band = { label: string; lower_bound: string; upper_bound: string };
type Version = { id: string; version: number; name: string; status: string; pass_threshold: string; criteria: Criterion[]; bands: Band[] };
type Rubric = { id: string; name: string; archived_at: string | null; versions: Version[] };
type Props = { rubrics: Rubric[] };
type Payload = { name: string; pass_threshold: string; criteria: Criterion[]; bands: Band[] };
type Event = { id: string; kind: 'penalty' | 'note'; criterion_id?: string; rule_id?: string; note?: string; active: boolean };
type Preview = { complete: boolean; display_score: string | null; unrounded_score: string | null; passed: boolean | null; grade: string | null; criteria: { id: string; name: string; computed_raw: string | null; effective_raw: string | null; normalized: string | null; weighted: string | null; deductions: { event_id: string; name: string; points: string }[] }[] };
const newCriterion = (): Criterion => ({ name: '', description: '', method: 'direct', min_score: '0', max_score: '100', weight: '100', min_pass_normalized: null, rules: [] });
const newRule = (): Rule => ({ name: '', severity_label: null, deduction_points: '5' });
const token = () => { const value = document.cookie.split('; ').find((part) => part.startsWith('XSRF-TOKEN='))?.split('=')[1]; return value ? decodeURIComponent(value) : ''; };

export default function RubricsIndex({ rubrics }: Props) {
    const form = useForm<Payload>({ name: '', pass_threshold: '80', criteria: [newCriterion()], bands: [] });
    const [editing, setEditing] = useState<{ rubric: string; version: string } | null>(null);
    const [selected, setSelected] = useState<{ rubric: string; version: Version } | null>(null);
    const [direct, setDirect] = useState<Record<string, string>>({});
    const [overrides, setOverrides] = useState<Record<string, { raw: string; reason: string }>>({});
    const [events, setEvents] = useState<Event[]>([]);
    const [preview, setPreview] = useState<Preview | null>(null);
    const [previewError, setPreviewError] = useState('');

    function criterion(index: number, change: Partial<Criterion>) { form.setData('criteria', form.data.criteria.map((item, i) => i === index ? { ...item, ...change } : item)); }
    function rule(index: number, ruleIndex: number, change: Partial<Rule>) { criterion(index, { rules: form.data.criteria[index].rules.map((item, i) => i === ruleIndex ? { ...item, ...change } : item) }); }
    function band(index: number, change: Partial<Band>) { form.setData('bands', form.data.bands.map((item, i) => i === index ? { ...item, ...change } : item)); }
    function submit(event: FormEvent) {
        event.preventDefault();
        const options = { preserveScroll: true, onSuccess: () => { form.reset(); setEditing(null); } };
        if (editing) form.put(`/rubrics/${editing.rubric}/versions/${editing.version}`, options);
        else form.post('/rubrics', options);
    }
    function edit(rubric: Rubric, version: Version) {
        setEditing({ rubric: rubric.id, version: version.id });
        form.setData({ name: version.name, pass_threshold: version.pass_threshold, criteria: version.criteria.map((item) => ({ ...item, description: item.description ?? '', min_pass_normalized: item.min_pass_normalized ?? null, rules: item.rules.map((entry) => ({ ...entry, severity_label: entry.severity_label ?? null })) })), bands: version.bands });
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
    function select(rubric: Rubric, version: Version) { setSelected({ rubric: rubric.id, version }); setDirect({}); setOverrides({}); setEvents([]); setPreview(null); setPreviewError(''); }
    async function calculate(final: boolean) {
        if (!selected) return;
        setPreviewError('');
        const response = await fetch(`/rubrics/${selected.rubric}/versions/${selected.version.id}/preview`, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-XSRF-TOKEN': token() }, body: JSON.stringify({ direct, overrides, events, final }) });
        if (response.ok) { setPreview(await response.json()); return; }
        const data = await response.json().catch(() => null) as { errors?: Record<string, string[]> } | null;
        setPreview(null);
        setPreviewError(Object.values(data?.errors ?? {}).flat().join(' ') || 'Pratinjau belum dapat dihitung.');
    }

    return <div className="master-shell"><Head title="Rubrik penilaian" /><a className="skip-link" href="#rubric-content">Lewati navigasi</a><header className="mushaf-header"><Link href="/dashboard">← Ringkasan</Link><span>Penilaian Tahfidz · Rubrik</span></header>
        <main id="rubric-content" className="master-main"><p className="eyebrow">F4 · Rubrik dan nilai</p><h1>Rubrik penilaian</h1><p className="muted">Atur kriteria dan potongan sesuai praktik Anda. Versi terbit tetap utuh saat membuat perubahan berikutnya.</p>
            <section className="master-card" aria-labelledby="builder-heading"><h2 id="builder-heading">{editing ? 'Ubah draf rubrik' : 'Buat rubrik'}</h2><form className="master-form" onSubmit={submit}>
                <div className="master-fields"><label>Nama rubrik<input required maxLength={160} value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} />{form.errors.name && <small role="alert">{form.errors.name}</small>}</label><label>Ambang lulus akhir (%)<input type="number" min="0" max="100" step="0.0001" value={form.data.pass_threshold} onChange={(e) => form.setData('pass_threshold', e.target.value)} />{form.errors.pass_threshold && <small role="alert">{form.errors.pass_threshold}</small>}</label></div>
                <h3>Kriteria</h3>{form.errors.criteria && <small role="alert">{form.errors.criteria}</small>}
                {form.data.criteria.map((item, index) => <fieldset className="master-card" key={index}><legend>Kriteria {index + 1}</legend><div className="master-fields">
                    <label>Nama<input required value={item.name} onChange={(e) => criterion(index, { name: e.target.value })} /></label><label>Metode<select value={item.method} onChange={(e) => criterion(index, { method: e.target.value as Criterion['method'], rules: e.target.value === 'direct' ? [] : item.rules })}><option value="direct">Nilai langsung</option><option value="deduction">Pengurangan</option></select></label>
                    <label>Minimum<input type="number" min="0" step="0.0001" value={item.min_score} onChange={(e) => criterion(index, { min_score: e.target.value })} /></label><label>Maksimum<input type="number" min="0" step="0.0001" value={item.max_score} onChange={(e) => criterion(index, { max_score: e.target.value })} /></label>
                    <label>Bobot (%)<input type="number" min="0" step="0.0001" value={item.weight} onChange={(e) => criterion(index, { weight: e.target.value })} /></label><label>Ambang kriteria (%) opsional<input type="number" min="0" max="100" step="0.0001" value={item.min_pass_normalized ?? ''} onChange={(e) => criterion(index, { min_pass_normalized: e.target.value || null })} /></label>
                </div><label>Deskripsi opsional<textarea value={item.description ?? ''} onChange={(e) => criterion(index, { description: e.target.value })} /></label>
                    {item.method === 'deduction' && <><h4>Aturan kesalahan</h4>{item.rules.map((entry, ruleIndex) => <div className="master-fields" key={ruleIndex}><label>Kesalahan<input required value={entry.name} onChange={(e) => rule(index, ruleIndex, { name: e.target.value })} /></label><label>Tingkat opsional<input value={entry.severity_label ?? ''} onChange={(e) => rule(index, ruleIndex, { severity_label: e.target.value || null })} /></label><label>Potongan<input type="number" min="0.0001" step="0.0001" value={entry.deduction_points} onChange={(e) => rule(index, ruleIndex, { deduction_points: e.target.value })} /></label><button type="button" onClick={() => criterion(index, { rules: item.rules.filter((_, i) => i !== ruleIndex) })}>Hapus aturan</button></div>)}<button type="button" onClick={() => criterion(index, { rules: [...item.rules, newRule()] })}>Tambah aturan</button></>}
                    <div>{form.data.criteria.length > 1 && <button type="button" onClick={() => form.setData('criteria', form.data.criteria.filter((_, i) => i !== index))}>Hapus kriteria</button>}</div>
                    {Object.entries(form.errors).filter(([key]) => key.startsWith(`criteria.${index}.`)).map(([key, message]) => <small key={key} role="alert">{message}</small>)}
                </fieldset>)}<button type="button" onClick={() => form.setData('criteria', [...form.data.criteria, { ...newCriterion(), weight: '0' }])}>Tambah kriteria</button>
                <h3>Predikat opsional</h3><p className="muted">Jika diisi, interval harus berurutan dari 0 sampai 100 tanpa celah atau tumpang tindih. Batas atas hanya masuk pada predikat terakhir.</p>{form.errors.bands && <small role="alert">{form.errors.bands}</small>}
                {form.data.bands.map((item, index) => <div className="master-fields" key={index}><label>Predikat<input required value={item.label} onChange={(e) => band(index, { label: e.target.value })} /></label><label>Dari<input type="number" min="0" max="100" step="0.0001" value={item.lower_bound} onChange={(e) => band(index, { lower_bound: e.target.value })} /></label><label>Sampai<input type="number" min="0" max="100" step="0.0001" value={item.upper_bound} onChange={(e) => band(index, { upper_bound: e.target.value })} /></label><button type="button" onClick={() => form.setData('bands', form.data.bands.filter((_, i) => i !== index))}>Hapus</button></div>)}
                <button type="button" onClick={() => form.setData('bands', [...form.data.bands, { label: '', lower_bound: form.data.bands.at(-1)?.upper_bound ?? '0', upper_bound: '100' }])}>Tambah predikat</button>
                <div className="master-actions"><button className="primary" disabled={form.processing}>{editing ? 'Simpan draf' : 'Buat draf'}</button>{editing && <button type="button" onClick={() => { setEditing(null); form.reset(); }}>Batal</button>}</div>
            </form></section>
            <section className="master-card" aria-labelledby="rubric-list-heading"><h2 id="rubric-list-heading">Daftar rubrik</h2>{rubrics.length === 0 && <p className="muted">Belum ada rubrik.</p>}{rubrics.map((rubric) => <article className="master-row" key={rubric.id}><div><h3>{rubric.name}{rubric.archived_at ? ' · Diarsipkan' : ''}</h3>{rubric.versions.map((version) => <p key={version.id}>Versi {version.version} · {version.status === 'published' ? 'Terbit' : version.status === 'retired' ? 'Riwayat' : 'Draf'} · {version.criteria.length} kriteria <span className="master-actions">{!rubric.archived_at && version.status === 'draft' && <><button type="button" onClick={() => edit(rubric, version)}>Ubah</button><button type="button" onClick={() => router.post(`/rubrics/${rubric.id}/versions/${version.id}/publish`)}>Terbitkan</button></>}{version.status !== 'draft' && <button type="button" onClick={() => select(rubric, version)}>Pratinjau nilai</button>}</span></p>)}{!rubric.archived_at && rubric.versions.every((version) => version.status !== 'draft') && <button type="button" onClick={() => router.post(`/rubrics/${rubric.id}/versions`)}>Buat versi baru</button>}{!rubric.archived_at && <button type="button" onClick={() => router.post(`/rubrics/${rubric.id}/archive`)}>Arsipkan rubrik</button>}</div></article>)}</section>
            {selected && <section className="master-card" aria-labelledby="preview-heading"><h2 id="preview-heading">Pratinjau nilai · {selected.version.name} v{selected.version.version}</h2><p className="muted">Pratinjau ini tidak menyimpan penilaian santri. Catatan biasa tidak mengurangi nilai; kejadian yang dibatalkan tidak dihitung.</p>{selected.version.criteria.map((criterion) => <div className="master-form" key={criterion.id}><h3>{criterion.name} · {criterion.method === 'direct' ? 'nilai langsung' : 'pengurangan'}</h3>{criterion.method === 'direct' ? <label>Nilai ({criterion.min_score}–{criterion.max_score})<input type="number" min={criterion.min_score} max={criterion.max_score} step="0.0001" value={direct[criterion.id ?? ''] ?? ''} onChange={(e) => setDirect({ ...direct, [criterion.id ?? '']: e.target.value })} /></label> : <div>{criterion.rules.map((rule) => <button key={rule.id} type="button" onClick={() => setEvents([...events, { id: crypto.randomUUID(), kind: 'penalty', criterion_id: criterion.id, rule_id: rule.id, active: true }])}>+ {rule.name} (−{rule.deduction_points})</button>)}</div>}
                    <div className="master-fields"><label>Override opsional<input type="number" min={criterion.min_score} max={criterion.max_score} step="0.0001" value={overrides[criterion.id ?? '']?.raw ?? ''} onChange={(e) => { const id = criterion.id ?? ''; const next = { ...overrides }; if (e.target.value) next[id] = { raw: e.target.value, reason: next[id]?.reason ?? '' }; else delete next[id]; setOverrides(next); }} /></label>{overrides[criterion.id ?? ''] && <label>Alasan override<input value={overrides[criterion.id ?? ''].reason} onChange={(e) => { const id = criterion.id ?? ''; setOverrides({ ...overrides, [id]: { ...overrides[id], reason: e.target.value } }); }} /></label>}</div>
                </div>)}<button type="button" onClick={() => setEvents([...events, { id: crypto.randomUUID(), kind: 'note', note: '', active: true }])}>Tambah catatan tanpa potongan</button><div className="master-list">{events.map((event) => <div key={event.id}><p>{event.kind === 'note' ? 'Catatan biasa' : selected.version.criteria.flatMap((criterion) => criterion.rules).find((rule) => rule.id === event.rule_id)?.name ?? 'Kesalahan'} · {event.active ? 'aktif' : 'dibatalkan'} {event.active && <button type="button" onClick={() => setEvents(events.map((item) => item.id === event.id ? { ...item, active: false } : item))}>Undo</button>}</p>{event.kind === 'note' && <label>Isi catatan<textarea maxLength={4000} value={event.note ?? ''} onChange={(e) => setEvents(events.map((item) => item.id === event.id ? { ...item, note: e.target.value } : item))} /></label>}</div>)}</div>
                <div className="master-actions"><button type="button" onClick={() => void calculate(false)}>Hitung draf</button><button className="primary" type="button" onClick={() => void calculate(true)}>Periksa hasil final</button><button type="button" onClick={() => setSelected(null)}>Tutup</button></div>{previewError && <p role="alert">{previewError}</p>}{preview && <div role="status"><h3>{preview.complete ? `${preview.display_score} · ${preview.passed ? 'Lulus' : 'Belum lulus'}` : 'Nilai belum lengkap'}</h3>{preview.grade && <p>Predikat: {preview.grade}</p>}{preview.complete && <p>Nilai sebelum pembulatan: {preview.unrounded_score}</p>}{preview.criteria.map((item) => <p key={item.id}><strong>{item.name}</strong>: hasil hitung {item.computed_raw ?? 'belum diisi'}, nilai efektif {item.effective_raw ?? '—'}, normalisasi {item.normalized ?? '—'}, kontribusi {item.weighted ?? '—'}{item.deductions.map((deduction) => <span key={deduction.event_id}> · {deduction.name} −{deduction.points}</span>)}</p>)}</div>}</section>}
        </main></div>;
}
